<?php

return [
    [
        'code' => 'badminton',
        'name' => '羽毛球',
        'require_number_of_people' => false,
        'area_choose_type' => 'chart',
        'area' => [
            '1' => 'B1',
            '2' => 'B4',
            '3' => 'B7',
            '4' => 'C1',
            '5' => 'C3',
            '6' => 'B2',
            '7' => 'B5',
            '8' => 'B8',
            '9' => 'C2',
            '10' => 'C4',
            '11' => 'B3',
            '12' => 'B6',
            '13' => 'B9',
            '14' => 'C5',
        ],
        'booking_date_after' => 'today',
        'booking_time_type' => 'hourly',
        'booking_time' => [
            ['start_from' => '09:00',
                'end_to' => '17:00'],
            ['start_from' => '17:00',
                'end_to' => '22:00'],
        ],
    ],
    [
        'code' => 'pingpong',
        'name' => '乒乓球',
        'require_number_of_people' => true,
        'area_choose_type' => 'chart',
        'area' => [
            '1' => 'P1',
            '2' => 'P2',
            '3' => 'P3',
            '4' => 'P4',
            '5' => 'P5',
            '6' => 'P6',
            '7' => 'P7',
            '8' => 'P8',
            '9' => 'P9',
            '10' => 'P10',
        ],
        'booking_date_after' => 'tomorrow',
        'booking_time_type' => 'hourly',
        'booking_time' => [
            ['start_from' => '09:00',
                'end_to' => '17:00'],
            ['start_from' => '17:00',
                'end_to' => '22:00'],
        ],
    ],
    [
        'code' => 'basketball',
        'name' => '篮球',
        'require_number_of_people' => false,
        'area_choose_type' => 'list',
        'area_choose_list_item' => [
            'all' => '全场',
            'half' => '半场',
        ],
        'area' => [
            '1' => 'lb1',
            '2' => 'lb2',
            '3' => 'lb3',
            '4' => 'lb4',
        ],
        'area_group' => [
            'lq1' => ['lb1', 'lb2'],
            'lq2' => ['lb3', 'lb4'],
        ],
        'booking_date_after' => 'tomorrow',
        'booking_time_type' => 'none',
        'booking_time' => [
            ['start_from' => '09:00',
                'end_to' => '17:00'],
            ['start_from' => '17:00',
                'end_to' => '22:00'],
        ],
    ],
];
