<?php

return [
    [
        'code' => 'badminton',
        'name' => '羽毛球',
        'require_number_of_people' => false,
        'area_choose_type' => 'chart',
        'area' => [
            '1' => 'b1',
            '2' => 'b4',
            '3' => 'b7',
            '4' => 'c1',
            '5' => 'c3',
            '6' => 'b2',
            '7' => 'b5',
            '8' => 'b8',
            '9' => 'c2',
            '10' => 'c4',
            '11' => 'b3',
            '12' => 'b6',
            '13' => 'b9',
            '14' => 'c5',
        ],
        'booking_date_after' => 'today',
        'booking_time_type' => 'hourly',
        'booking_time' => [
            ['start_from' => '09:00',
                'end_to' => '17:00'],
            ['start_from' => '17:00',
                'end_to' => '22:00'],
        ],
    ],
    [
        'code' => 'pingpong',
        'name' => '乒乓球',
        'require_number_of_people' => true,
        'area_choose_type' => 'chart',
        'area' => [
            '1' => 'p1',
            '2' => 'p2',
            '3' => 'p3',
            '4' => 'p4',
            '5' => 'p5',
            '6' => 'p6',
            '7' => 'p7',
            '8' => 'p8',
            '9' => 'p9',
            '10' => 'p10',
        ],
        'booking_date_after' => 'tomorrow',
        'booking_time_type' => 'hourly',
        'booking_time' => [
            ['start_from' => '09:00',
                'end_to' => '17:00'],
            ['start_from' => '17:00',
                'end_to' => '22:00'],
        ],
    ],
    [
        'code' => 'basketball',
        'name' => '篮球',
        'require_number_of_people' => false,
        'area_choose_type' => 'list',
        'area_choose_list_item' => [
            'all' => '全场',
            'half' => '半场',
        ],
        'area' => [
            '1' => 'k1',
            '2' => 'k2',
            '3' => 'k3',
            '4' => 'k4',
        ],
        'booking_date_after' => 'tomorrow',
        'booking_time_type' => 'none',
        'booking_time' => [
            ['start_from' => '09:00',
                'end_to' => '17:00'],
            ['start_from' => '17:00',
                'end_to' => '22:00'],
        ],
    ],
];
